version: "3.8"

services:
  olx-db:
    image: postgres:15-alpine
    container_name: olx-microservice-db
    ports:
      - "5439:5432"
    environment:
      POSTGRES_DB: olx_microservice
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - olx_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  olx_db_data:
