services:
  rabbitmq:
    image: rabbitmq:3.12-management
    container_name: ai-gift-finder-rabbitmq
    ports:
      - "5672:5672" # AMQP port
      - "15672:15672" # Management UI port
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - ai-present-finder-network
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3

  reranking-postgres:
    image: postgres:16
    container_name: ai-gift-finder-reranking-postgres
    ports:
      - "5633:5432"
    environment:
      POSTGRES_DB: reranking_service
      POSTGRES_USER: reranking_user
      POSTGRES_PASSWORD: reranking_password
    volumes:
      - reranking_postgres_data:/var/lib/postgresql/data
    networks:
      - ai-present-finder-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U reranking_user -d reranking_service"]
      interval: 30s
      timeout: 10s
      retries: 3

  fetch-postgres:
    image: postgres:16
    container_name: ai-gift-finder-fetch-postgres
    ports:
      - "5434:5432"
    environment:
      POSTGRES_DB: fetch_service
      POSTGRES_USER: fetch_user
      POSTGRES_PASSWORD: fetch_password
    volumes:
      - fetch_postgres_data:/var/lib/postgresql/data
    networks:
      - ai-present-finder-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U fetch_user -d fetch_service"]
      interval: 30s
      timeout: 10s
      retries: 3

  stalking-postgres:
    image: postgres:16
    container_name: ai-gift-finder-stalking-postgres
    ports:
      - "6435:5432"
    environment:
      POSTGRES_DB: stalking_service
      POSTGRES_USER: stalking_user
      POSTGRES_PASSWORD: stalking_password
    volumes:
      - stalking_postgres_data:/var/lib/postgresql/data
    networks:
      - ai-present-finder-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U stalking_user -d stalking_service"]
      interval: 30s
      timeout: 10s
      retries: 3

  chat-postgres:
    image: postgres:16
    container_name: ai-gift-finder-chat-postgres
    ports:
      - "6436:5432"
    environment:
      POSTGRES_DB: chat_service
      POSTGRES_USER: chat_user
      POSTGRES_PASSWORD: chat_password
    volumes:
      - chat_postgres_data:/var/lib/postgresql/data
    networks:
      - ai-present-finder-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U chat_user -d chat_service"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  rabbitmq_data:
  reranking_postgres_data:
  fetch_postgres_data:
  stalking_postgres_data:
  chat_postgres_data:

networks:
  ai-present-finder-network:
    driver: bridge
