version: "3.8"

services:
  rabbitmq:
    image: rabbitmq:3.12-management
    container_name: ai-gift-finder-rabbitmq
    ports:
      - "5672:5672" # AMQP port
      - "15672:15672" # Management UI port
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - ai-present-finder-network
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3

  # PostgreSQL Databases for each microservice
  gift-db:
    image: postgres:15-alpine
    container_name: ai-gift-finder-gift-db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: gift_microservice
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - gift_db_data:/var/lib/postgresql/data
    networks:
      - ai-present-finder-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  allegro-db:
    image: postgres:15-alpine
    container_name: ai-gift-finder-allegro-db
    ports:
      - "5434:5432"
    environment:
      POSTGRES_DB: allegro_microservice
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - allegro_db_data:/var/lib/postgresql/data
    networks:
      - ai-present-finder-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  amazon-db:
    image: postgres:15-alpine
    container_name: ai-gift-finder-amazon-db
    ports:
      - "5435:5432"
    environment:
      POSTGRES_DB: amazon_microservice
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - amazon_db_data:/var/lib/postgresql/data
    networks:
      - ai-present-finder-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  chat-db:
    image: postgres:15-alpine
    container_name: ai-gift-finder-chat-db
    ports:
      - "5436:5432"
    environment:
      POSTGRES_DB: chat_microservice
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - chat_db_data:/var/lib/postgresql/data
    networks:
      - ai-present-finder-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  ebay-db:
    image: postgres:15-alpine
    container_name: ai-gift-finder-ebay-db
    ports:
      - "5437:5432"
    environment:
      POSTGRES_DB: ebay_microservice
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ebay_db_data:/var/lib/postgresql/data
    networks:
      - ai-present-finder-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  olx-db:
    image: postgres:15-alpine
    container_name: ai-gift-finder-olx-db
    ports:
      - "5438:5432"
    environment:
      POSTGRES_DB: olx_microservice
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - olx_db_data:/var/lib/postgresql/data
    networks:
      - ai-present-finder-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  stalking-db:
    image: postgres:15-alpine
    container_name: ai-gift-finder-stalking-db
    ports:
      - "5439:5432"
    environment:
      POSTGRES_DB: stalking_microservice
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - stalking_db_data:/var/lib/postgresql/data
    networks:
      - ai-present-finder-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  restapi-db:
    image: postgres:15-alpine
    container_name: ai-gift-finder-restapi-db
    ports:
      - "5440:5432"
    environment:
      POSTGRES_DB: restapi_macroservice
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - restapi_db_data:/var/lib/postgresql/data
    networks:
      - ai-present-finder-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  rabbitmq_data:
  gift_db_data:
  allegro_db_data:
  amazon_db_data:
  chat_db_data:
  ebay_db_data:
  olx_db_data:
  stalking_db_data:
  restapi_db_data:

networks:
  ai-present-finder-network:
    driver: bridge
