packages:
  - core/events
  - core/types
  - core/rabbitmq-config
  - backend/chat-microservice
  - backend/fetch-microservice
  - backend/gift-ideas-microservice
  - backend/restapi-macroservice
  - backend/stalking-microservice
  - backend/reranking-microservice
  - frontend

injectWorkspacePackages: true

onlyBuiltDependencies:
  - "@nestjs/core"
  - "@swc/core"
  - "@tailwindcss/oxide"
  - bcrypt
  - cpu-features
  - esbuild
  - msw
  - protobufjs
  - ssh2

syncInjectedDepsAfterScripts:
  - build
