packages:
  - backend/chat-microservice
  - backend/gift-microservice
  - backend/restapi-macroservice
  - backend/stalking-microservice
  - frontend

onlyBuiltDependencies:
  - "@nestjs/core"
  - "@swc/core"
  - "@tailwindcss/oxide"
  - esbuild
