packages:
  - backend/core-events
  - backend/chat-microservice
  - backend/fetch-microservice
  - backend/gift-ideas-microservice
  - backend/restapi-macroservice
  - backend/stalking-microservice
  - backend/reranking-microservice
  - frontend

onlyBuiltDependencies:
  - "@nestjs/core"
  - "@swc/core"
  - "@tailwindcss/oxide"
  - esbuild
