packages:
  - backend/chat-microservice
  - backend/gift-microservice
  - backend/restapi-macroservice
  - backend/stalking-microservice
  - backend/olx-microservice
  - backend/allegro-microservice
  - backend/amazon-microservice
  - backend/ebay-microservice
  - frontend

onlyBuiltDependencies:
  - "@nestjs/core"
  - "@swc/core"
  - "@tailwindcss/oxide"
  - esbuild
