version: "3.8"

services:
  chat-db:
    image: postgres:15-alpine
    container_name: chat-microservice-db
    ports:
      - "5436:5432"
    environment:
      POSTGRES_DB: chat_microservice
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - chat_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  chat_db_data:
