version: "3.8"

services:
  gift-db:
    image: postgres:15-alpine
    container_name: gift-microservice-db
    ports:
      - "5438:5432"
    environment:
      POSTGRES_DB: gift_microservice
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - gift_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  gift_db_data:
