version: "3.8"

services:
  amazon-db:
    image: postgres:15-alpine
    container_name: amazon-microservice-db
    ports:
      - "5435:5432"
    environment:
      POSTGRES_DB: amazon_microservice
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - amazon_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  amazon_db_data:
