module.exports = {
  apps: [
    {
      name: "restapi-macroservice",
      cwd: "./backend/restapi-macroservice",
      script: "dist/backend/restapi-macroservice/src/main.js",
      instances: 1,
      exec_mode: "cluster",
      env: {
        NODE_ENV: "production",
        PORT: process.env.RESTAPI_PORT || 3000,
      },
    },
    {
      name: "stalking-microservice",
      cwd: "./backend/stalking-microservice",
      script: "dist/backend/stalking-microservice/src/main.js",
      instances: 1,
      exec_mode: "cluster",
      env: {
        NODE_ENV: "production",
        PORT: process.env.STALKING_PORT || 3010,
        DATABASE_URL: process.env.STALKING_DATABASE_URL,
      },
    },
    {
      name: "chat-microservice",
      cwd: "./backend/chat-microservice",
      script: "dist/backend/chat-microservice/src/main.js",
      instances: 1,
      exec_mode: "cluster",
      env: {
        NODE_ENV: "production",
        PORT: process.env.CHAT_PORT || 3020,
        DATABASE_URL: process.env.CHAT_DATABASE_URL,
      },
    },
    {
      name: "gift-microservice",
      cwd: "./backend/gift-microservice",
      script: "dist/main.js",
      instances: 1,
      exec_mode: "cluster",
      env: {
        NODE_ENV: "production",
        PORT: process.env.GIFT_PORT || 3030,
      },
    },
    {
      name: "gift-ideas-microservice",
      cwd: "./backend/gift-ideas-microservice",
      script: "dist/backend/gift-ideas-microservice/src/main.js",
      instances: 1,
      exec_mode: "cluster",
      env: {
        NODE_ENV: "production",
        PORT: process.env.GIFT_IDEAS_PORT || 3040,
        DATABASE_URL: process.env.GIFT_IDEAS_DATABASE_URL,
      },
    },
    {
      name: "reranking-microservice",
      cwd: "./backend/reranking-microservice",
      script: "dist/backend/reranking-microservice/src/main.js",
      instances: 1,
      exec_mode: "cluster",
      env: {
        NODE_ENV: "production",
        PORT: process.env.RERANKING_PORT || 3050,
        DATABASE_URL: process.env.RERANKING_DATABASE_URL,
      },
    },
    {
      name: "fetch-microservice-olx",
      cwd: "./backend/fetch-microservice",
      script: "dist/backend/fetch-microservice/src/main.js",
      instances: 1,
      exec_mode: "cluster",
      env: {
        NODE_ENV: "production",
        PORT: process.env.FETCH_OLX_PORT || 8011,
        FETCH_PROVIDER: "olx",
        DATABASE_URL: process.env.FETCH_DATABASE_URL,
      },
    },
    {
      name: "fetch-microservice-allegro",
      cwd: "./backend/fetch-microservice",
      script: "dist/backend/fetch-microservice/src/main.js",
      instances: 1,
      exec_mode: "cluster",
      env: {
        NODE_ENV: "production",
        PORT: process.env.FETCH_ALLEGRO_PORT || 8012,
        FETCH_PROVIDER: "allegro",
        DATABASE_URL: process.env.FETCH_DATABASE_URL,
      },
    },
    {
      name: "fetch-microservice-ebay",
      cwd: "./backend/fetch-microservice",
      script: "dist/backend/fetch-microservice/src/main.js",
      instances: 1,
      exec_mode: "cluster",
      env: {
        NODE_ENV: "production",
        PORT: process.env.FETCH_EBAY_PORT || 8013,
        FETCH_PROVIDER: "ebay",
        DATABASE_URL: process.env.FETCH_DATABASE_URL,
      },
    },
    {
      name: "fetch-microservice-amazon",
      cwd: "./backend/fetch-microservice",
      script: "dist/backend/fetch-microservice/src/main.js",
      instances: 1,
      exec_mode: "cluster",
      env: {
        NODE_ENV: "production",
        PORT: process.env.FETCH_AMAZON_PORT || 8014,
        FETCH_PROVIDER: "amazon",
        DATABASE_URL: process.env.FETCH_DATABASE_URL,
      },
    },
  ],
};
