version: "3.8"

services:
  restapi-db:
    image: postgres:15-alpine
    container_name: restapi-macroservice-db
    ports:
      - "5440:5432"
    environment:
      POSTGRES_DB: restapi_macroservice
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - restapi_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  restapi_db_data:
