version: "3.8"

services:
  stalking-db:
    image: postgres:15-alpine
    container_name: stalking-microservice-db
    ports:
      - "5441:5432"
    environment:
      POSTGRES_DB: stalking_microservice
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - stalking_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  stalking_db_data:
