version: "3.8"

services:
  allegro-db:
    image: postgres:15-alpine
    container_name: allegro-microservice-db
    ports:
      - "5434:5432"
    environment:
      POSTGRES_DB: allegro_microservice
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - allegro_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  allegro_db_data:
